### ISSUE TITLE
Bug in "searchthebucket"

### ISSUE THREAD

**Issue by casual1** [Flamezzz/FClueHunterEasy#14]
Search the bucket in port sarim jail.

It went down to shantay pass and kept clicking the shantay guy for a minute.

**Comment by Flamezzz** [comment]
Did it do anything of the dialogue? I've noticed it can sometimes take a while but never really fails.

Do you have a log?

**Comment by casual1** [comment]
couldn't see because of the advert lol. saw the red cursor clicks on the guy though.. can't seem to reproduce it, I think this is the first time I faced this clue text in like 100 clues

if it was gonna start the dialogue, it's okay

**Comment by Flamezzz** [comment]
Mhm... I'll try to reproduce it, thanks for reporting this issue :)

**Comment by Flamezzz** [comment]
I was unable to reproduce this, closing it for now.

**Comment by casual1** [comment]
I guess there's an additional chat line for those who didn't complete one of the desert quests, that the shantay notices a girl crying next to the pass and tells you. Will check next time I get there.
